### ISSUE TITLE
Events directly after each other not rendering properly

### ISSUE THREAD

**Issue by tannery-cerebras** [google/perfetto#443] opened 2023-02-07 17:24 UTC
I am using `v31.0-cf5c9` and this issues exists on canary `v31.0-14a08` as well.
[trace.pb.zip](https://github.com/google/perfetto/files/10677753/trace.pb.zip)

In the attached protobuf file (sorry its big), I have the event `Reduce` and `DRelu` that, based on their start time and duration, should be right beside each other.

However, there is a gap between them:
`Reduce` starts at `25us 840ns` with a duration of `155ns`
`DRelu` (and `TxAct`) start at `25us 995ns`.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/105221472/217316512-29c05621-1c18-4c1d-866f-618526dec860.png">

<img width="891" alt="image" src="https://user-images.githubusercontent.com/105221472/217316568-97590c60-1aa4-402c-b413-67c1965fa7b8.png">

**Comment by LalitMaganti** [comment] 2023-02-07 17:34
Duplicate of https://github.com/google/perfetto/issues/282

**Closed by LalitMaganti** 2023-02-07 17:34 UTC
