### ISSUE TITLE
Perfetto does not sort concurrent events in a thread as well as chrome

### ISSUE THREAD

**Issue by kerrybbarnes** [google/perfetto#503] opened 2023-05-27 17:04 UTC
The following trace file views better in chrome than in perfetto.   The problem is that long events that have subevents in them are not always stacked above the sub-events.  Worse some of the events are overlapping on the same line.

[TRACE_EVENT_RANK1_TIME1685205908_SERIAL1.gz](https://github.com/google/perfetto/files/11582569/TRACE_EVENT_RANK1_TIME1685205908_SERIAL1.gz)

**Comment by kerrybbarnes** [comment] 2023-05-27 17:08
Compare the screenshot of perfetto vs chrome
![image](https://github.com/google/perfetto/assets/91760353/78bafd93-c25a-4d07-b964-67e9c5518bdf)

**Comment by kerrybbarnes** [comment] 2023-11-10 14:01
Is there a workaround - Is there some sorting of the events in the Trace file that would allow perfetto to display the events correctly?

**Comment by LalitMaganti** [comment] 2023-11-10 14:34
Had a look at your trace. The problem appears to be that the entire trace is composed of "X" events but those events are not perfectly nesting in each other but overlapping. This breaks the JSON specification and this exact question is covered in our [FAQ](https://perfetto.dev/docs/faq#why-are-overlapping-events-in-json-traces-not-displayed-correctly-).

Note that chrome://tracing is actually **rendering the data incorrectly***. This is not a bug in the Perfetto UI but a bug in chrome://tracing in being too lenient in what it accepts and then showing the wrong thing to the user.

Two options to fixing this:
1) (preferred) Use the Perfetto native format and represent these events as process-scoped slices (see [here](https://perfetto.dev/docs/reference/synthetic-track-event#process-scoped-async-slices))
2) Use the nestable async event functionality of the JSON format (see [here](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.yr4qxyxotyw)).

Closing this bug as there is no actual issue on the Perfetto side.

**Closed by LalitMaganti** 2023-11-10 14:34 UTC

**Comment by kerrybbarnes** [comment] 2023-11-13 22:13
Thanks - and now that you point it out I can see it.  Been running chrome tracer for some years now and that incorrect behavior was working for m.   So the problem is on my end then - there should be no overlaps the way the information is corrected so fixing that bug should resolve the problem.
