### ISSUE TITLE
Value is incorrect when used tmw counter format

### ISSUE THREAD

**Issue by miraclemore** [google/perfetto#966] opened 2024-12-17 08:08 UTC
I customized some tmw trace in my local.
eg: tracing_mark_write: C|10000|ABC|410001510900020103

Then we capature systrace by atrace tool.
For the raw data text,  ftrace show 19737.075274: tracing_mark_write: C|10000|abc|**719201510900040202** (VALUE1)

If we drop the trace to the perfetto UI, then the track counter show **719,201,482,125,082,600** (VALUE2)
And also for the bottom message by current selected is shown as 

Name abc
Start time 19737075274000
Value **719,201,510,900,040,200** (VALUE3)
Delta 719,175,999,998,998,000
Duration 739000

I regard that the above thress value should be same, but current VALUE1 != VALUE2 != VALUE3.
Could u help to check that ?

**Comment by LalitMaganti** [comment] 2024-12-17 13:23
The root cause of all of this is that is larger than the max value properly representible by a double. Specifically you can see VALUE1 and VALUE3 differ by only 2. This is because VALUE1 is *not* properly representable as a double and so cannot be shown correctly by the UI. This is fundamental to how tracing_mark_write parsing works.

VALUE2 and VALUE3 differing is a bug and should be fixed. I'll look into that.

**Comment by LalitMaganti** [comment] 2024-12-17 13:24
Would help if you could provide a small trace which shows the issue to look into this.

**Comment by miraclemore** [comment] 2024-12-18 06:34
@LalitMaganti 
pls refer to the below pic as an example.
<img width="1029" alt="Image" src="https://github.com/user-attachments/assets/8b1c3b8f-f88a-4ebc-84cc-9c3762e784ab" />
And also you can try the below systrace to check the value for 10000 tacker
[trace.systrace.zip](https://github.com/user-attachments/files/18176120/trace.systrace.zip)

**Comment by LalitMaganti** [comment] 2024-12-20 14:28
https://r.android.com/3426866 will fix the difference between hover display and bottom panel display.

There is still the problem of those values being too big to properly fit in a double that we cannot really do anything about. You are going to lose some precision with such large values, it's inevitable.

**Closed** 2024-12-20 15:01 UTC
Labels: bug
