### ISSUE TITLE
Config android.surfaceflinger.frame is not working

### ISSUE THREAD

**Issue by fraisty** [google/perfetto#144] opened 2021-06-08 14:39 UTC
Hi~
i want to use the android.surfaceflinger.frame configuration for debugging, so i  add it to the trace config, like this:
data_sources: {
    config {
        name: "android.surfaceflinger.frame"
    }
}
but i found that the configuration did not work. I did not see any diff, no matter whether i added it or not.
Is there i missing some extra configuration?
thanks.

**Comment by LalitMaganti** [comment] 2021-06-08 15:56
First, as specified in our docs (at https://perfetto.dev/docs/data-sources/frametimeline#traceconfig), the correct config is:
```
data_sources {
    config {
        name: "android.surfaceflinger.frametimeline"
    }
}
```
(i.e. frametimeline *not* frame)

Secondly, this is only available on S+ devices so ensure you are running on S DP or Beta for this to work

**Comment by fraisty** [comment] 2021-06-08 16:42
Dear LalitMaganti~
Thank u for your reply.
But as I khow, I think android.surfaceflinger.frametimeline and android.surfaceflinger.frame are different.
in perfetto docs, the tracepacket is not same:
frametimeline:(https://perfetto.dev/docs/reference/trace-packet-proto#FrameTimelineEvent)
graphicsframe:(https://perfetto.dev/docs/reference/trace-packet-proto#GraphicsFrameEvent)
I currently am running on S devices for this, and frametimeline is working normally,but graphicsframe is not.

**Comment by LalitMaganti** [comment] 2021-06-08 17:23
Apologies - I forgot about GraphicsFrameEvent was named `android.surfaceflinger.frame` and not something with the word graphics.

This is actually a UI issue - the issue is collected correctly by Perfetto and parsed by trace processor; the UI is just now showing the track. Will send a patch.

**Comment by LalitMaganti** [comment] 2021-06-08 20:34
This is fixed by https://android-review.googlesource.com/c/platform/external/perfetto/+/1730338 which should roll out to the stable UI in the next couple of weeks.

**Closed by LalitMaganti** 2021-06-08 20:34 UTC
