### ISSUE TITLE
Use Perfetto to visualise parent-child relationship

### ISSUE THREAD

**Issue by facewindu** [google/perfetto#896] opened 2024-09-24 11:39 UTC
I'm using Perfetto SDK to visualise custom track events based on my own modelling system.
Roughly speaking, we have events like the following
```
[ Event 1                  ]
      [ Event 2 ]
```
So they are nested, and I can assign my track events to the same track (same process/thread id), which perfectly does the job.

Now, I can be in a situation where child events are executed in parallel, e.g.
```
[ Event 1                  ]
   [ Event 2.1 ]
      [ Event 2.2     ]
```
In reality, `Event 2.1` and `Event 2.2` are executed on separate threads. In Perfetto, this means using a separate thread ID for them. This is fine, but then (and maybe I missed something), I find it hard to visualize the parent-child relationship between say `Event 1` and `Event 2.2` (executed in a separate thread, so visually on a separate track).

I tried using `Flows`, but the arrows are displayed between the end of the 'from' slice to the beginning of the 'end' slice, so it's not really helping (the arrow would go here from the end of `Event 1` to the beginning of `Event 2.1` and `Event 2.2`).
I could also replace the slice of `Event 1` to be two instants (for its beginning and end), and have a flow between the beginning instance and the slices for the child events, but I don't want to lose the fact that my event 1 is a full-fledged slice, and not just an instant thing.

I know that Perfetto is not really designed to deal with this kind of representation, but do you think of a way to help in this case?

**Comment by LalitMaganti** [comment] 2024-09-24 11:52
So at the SDK level, the answer is:
1) use process tracks for all events
2) make the child event set the parent_uuid field equal to the track UUID of the parent event

The main problem is that the UI currently does not handle track nesting properly. Fortunately we've been aware of this problem and there is a change in review (https://android-review.googlesource.com/c/platform/external/perfetto/+/3258215/20) which solves this very issue. There will need to be a follow up change where move the SDK tracks to actually display properly in this new world but once that's done, you should have something which does what you want (visualize async work with parent child relationships).

**Comment by LalitMaganti** [comment] 2024-09-24 11:52
@stevegolton

**Comment by facewindu** [comment] 2024-09-24 14:08
> So at the SDK level, the answer is:
> 
> 1. use process tracks for all events
> 2. make the child event set the parent_uuid field equal to the track UUID of the parent event
> 
> The main problem is that the UI currently does not handle track nesting properly. Fortunately we've been aware of this problem and there is a change in review (https://android-review.googlesource.com/c/platform/external/perfetto/+/3258215/20) which solves this very issue. There will need to be a follow up change where move the SDK tracks to actually display properly in this new world but once that's done, you should have something which does what you want (visualize async work with parent child relationships).

awesome !
thanks

**Comment by LalitMaganti** [comment] 2024-09-25 13:17
Sure.

> Will it require updating my perfetto-proto dependency ? I'm currently on 43.2.

I don't think so but let's see.

**Comment by LalitMaganti** [comment] 2024-09-26 10:31
https://r.android.com/3283437 has landed which I believe was the last piece needed to nest tracks in the way that you want, please try it out and let us know how it is :)

**Closed by LalitMaganti** 2024-09-26 10:31 UTC

**Comment by facewindu** [comment] 2024-09-26 14:53
Is it already on https://ui.perfetto.dev/ (canary) ?

**Comment by LalitMaganti** [comment] 2024-09-26 15:01
It's in autopush (you can change to autopush by going to flags and changing the release channel to autopush).

**Comment by facewindu** [comment] 2024-09-26 15:11
ah, thanks, I forgot `autopush` had moved from the front page.

Then I'm seeing sth strange
See this trace
```
packet {
  clock_snapshot {
    clocks {
      clock_id: 64
      timestamp: 0
      unit_multiplier_ns: 1000000
    }
    clocks {
      clock_id: 6
      timestamp: 0
    }
  }
  trusted_packet_sequence_id: 1
}
packet {
  timestamp: 0
  trusted_packet_sequence_id: 1
  interned_data {
    event_categories {
      iid: 1
      name: "BuildStarted"
    }
    event_categories {
      iid: 2
      name: "ProjectEvaluationStarted"
    }
    event_categories {
      iid: 3
      name: "ScriptApplicationStarted"
    }
    event_names {
      iid: 1
      name: "Build"
    }
    event_names {
      iid: 2
      name: "Project evaluation for :proj-1"
    }
    event_names {
      iid: 3
      name: "Project evaluation for :proj-2"
    }
    event_names {
      iid: 4
      name: "Script application for myfile-2"
    }
    event_names {
      iid: 5
      name: "Project evaluation for :proj-1-1"
    }
    event_names {
      iid: 6
      name: "Script application for myfile-1_1"
    }
    event_names {
      iid: 7
      name: "Project evaluation for :proj-3"
    }
    event_names {
      iid: 8
      name: "Project evaluation for :proj-4"
    }
    event_names {
      iid: 9
      name: "Script application for myfile-3"
    }
    debug_annotation_names {
      iid: 1
      name: "com.gradle.scan.eventmodel.gradle.BuildStarted_1_0"
    }
    debug_annotation_names {
      iid: 2
      name: "com.gradle.scan.eventmodel.gradle.ProjectEvaluationStarted_1_1"
    }
    debug_annotation_names {
      iid: 3
      name: "projectPath"
    }
    debug_annotation_names {
      iid: 4
      name: "buildPath"
    }
    debug_annotation_names {
      iid: 5
      name: "com.gradle.scan.eventmodel.gradle.ScriptApplicationStarted_1_0"
    }
    debug_annotation_names {
      iid: 6
      name: "id"
    }
    debug_annotation_names {
      iid: 7
      name: "targetType"
    }
    debug_annotation_names {
      iid: 8
      name: "targetPath"
    }
    debug_annotation_names {
      iid: 9
      name: "file"
    }
    debug_annotation_names {
      iid: 10
      name: "root"
    }
    debug_annotation_names {
      iid: 11
      name: "path"
    }
    debug_annotation_names {
      iid: 12
      name: "uri"
    }
    debug_annotation_names {
      iid: 13
      name: "com.gradle.scan.eventmodel.gradle.ScriptApplicationFinished_1_0"
    }
    debug_annotation_names {
      iid: 14
      name: "com.gradle.scan.eventmodel.gradle.ProjectEvaluationFinished_1_2"
    }
    debug_annotation_names {
      iid: 15
      name: "failure"
    }
    debug_annotation_names {
      iid: 16
      name: "failureId"
    }
    debug_annotation_names {
      iid: 17
      name: "com.gradle.scan.eventmodel.gradle.BuildFinished_1_1"
    }
    debug_annotation_string_values {
      iid: 1
      str: ":proj-1"
    }
    debug_annotation_string_values {
      iid: 2
      str: ":"
    }
    debug_annotation_string_values {
      iid: 3
      str: ":proj-2"
    }
    debug_annotation_string_values {
      iid: 4
      str: "1"
    }
    debug_annotation_string_values {
      iid: 5
      str: "project"
    }
    debug_annotation_string_values {
      iid: 6
      str: "WORKSPACE"
    }
    debug_annotation_string_values {
      iid: 7
      str: "myfile-2"
    }
    debug_annotation_string_values {
      iid: 8
      str: ""
    }
    debug_annotation_string_values {
      iid: 9
      str: ":proj-1-1"
    }
    debug_annotation_string_values {
      iid: 10
      str: "2"
    }
    debug_annotation_string_values {
      iid: 11
      str: "myfile-1_1"
    }
    debug_annotation_string_values {
      iid: 12
      str: ":proj-3"
    }
    debug_annotation_string_values {
      iid: 13
      str: ":proj-4"
    }
    debug_annotation_string_values {
      iid: 14
      str: "3"
    }
    debug_annotation_string_values {
      iid: 15
      str: "myfile-3"
    }
  }
  sequence_flags: 1
  previous_packet_dropped: true
  timestamp_clock_id: 64
  first_packet_on_sequence: true
}
packet {
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 1
    name: "Build"
    process {
      pid: 0
      process_name: "Build"
    }
  }
}
packet {
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 1
    name: "Build"
    parent_uuid: 1
  }
}
packet {
  timestamp: 0
  trusted_packet_sequence_id: 1
  track_event {
    category_iids: 1
    debug_annotations {
      name_iid: 1
    }
    type: TYPE_SLICE_BEGIN
    name_iid: 1
    track_uuid: 1
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 2
    name: "Build"
    parent_uuid: 1
  }
}
packet {
  timestamp: 1
  trusted_packet_sequence_id: 1
  track_event {
    category_iids: 2
    debug_annotations {
      name_iid: 2
      dict_entries {
        name_iid: 3
        string_value_iid: 1
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
    }
    type: TYPE_SLICE_BEGIN
    name_iid: 2
    track_uuid: 2
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 3
    name: "Build"
    parent_uuid: 1
  }
}
packet {
  timestamp: 1
  trusted_packet_sequence_id: 1
  track_event {
    category_iids: 2
    debug_annotations {
      name_iid: 2
      dict_entries {
        name_iid: 3
        string_value_iid: 3
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
    }
    type: TYPE_SLICE_BEGIN
    name_iid: 3
    track_uuid: 3
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 4
    name: "Build"
    parent_uuid: 3
  }
}
packet {
  timestamp: 1
  trusted_packet_sequence_id: 1
  track_event {
    category_iids: 3
    debug_annotations {
      name_iid: 5
      dict_entries {
        name_iid: 6
        string_value_iid: 4
      }
      dict_entries {
        name_iid: 7
        string_value_iid: 5
      }
      dict_entries {
        name_iid: 8
        string_value_iid: 3
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
      dict_entries {
        name_iid: 9
        dict_entries {
          name_iid: 10
          string_value_iid: 6
        }
        dict_entries {
          name_iid: 11
          string_value_iid: 7
        }
      }
      dict_entries {
        name_iid: 12
        string_value_iid: 8
      }
    }
    type: TYPE_SLICE_BEGIN
    name_iid: 4
    track_uuid: 4
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 5
    name: "Build"
    parent_uuid: 1
  }
}
packet {
  timestamp: 3
  trusted_packet_sequence_id: 1
  track_event {
    category_iids: 2
    debug_annotations {
      name_iid: 2
      dict_entries {
        name_iid: 3
        string_value_iid: 9
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
    }
    type: TYPE_SLICE_BEGIN
    name_iid: 5
    track_uuid: 5
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 6
    name: "Build"
    parent_uuid: 5
  }
}
packet {
  timestamp: 3
  trusted_packet_sequence_id: 1
  track_event {
    category_iids: 3
    debug_annotations {
      name_iid: 5
      dict_entries {
        name_iid: 6
        string_value_iid: 10
      }
      dict_entries {
        name_iid: 7
        string_value_iid: 5
      }
      dict_entries {
        name_iid: 8
        string_value_iid: 9
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
      dict_entries {
        name_iid: 9
        dict_entries {
          name_iid: 10
          string_value_iid: 6
        }
        dict_entries {
          name_iid: 11
          string_value_iid: 11
        }
      }
      dict_entries {
        name_iid: 12
        string_value_iid: 8
      }
    }
    type: TYPE_SLICE_BEGIN
    name_iid: 6
    track_uuid: 6
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  timestamp: 4
  trusted_packet_sequence_id: 1
  track_event {
    debug_annotations {
      name_iid: 13
      dict_entries {
        name_iid: 6
        string_value_iid: 10
      }
    }
    type: TYPE_SLICE_END
    track_uuid: 6
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  timestamp: 4
  trusted_packet_sequence_id: 1
  track_event {
    debug_annotations {
      name_iid: 14
      dict_entries {
        name_iid: 3
        string_value_iid: 9
      }
      dict_entries {
        name_iid: 15
        string_value_iid: 8
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
      dict_entries {
        name_iid: 16
        string_value_iid: 8
      }
    }
    type: TYPE_SLICE_END
    track_uuid: 5
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  timestamp: 5
  trusted_packet_sequence_id: 1
  track_event {
    debug_annotations {
      name_iid: 14
      dict_entries {
        name_iid: 3
        string_value_iid: 1
      }
      dict_entries {
        name_iid: 15
        string_value_iid: 8
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
      dict_entries {
        name_iid: 16
        string_value_iid: 8
      }
    }
    type: TYPE_SLICE_END
    track_uuid: 2
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  timestamp: 5
  trusted_packet_sequence_id: 1
  track_event {
    debug_annotations {
      name_iid: 13
      dict_entries {
        name_iid: 6
        string_value_iid: 4
      }
    }
    type: TYPE_SLICE_END
    track_uuid: 4
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  timestamp: 6
  trusted_packet_sequence_id: 1
  track_event {
    debug_annotations {
      name_iid: 14
      dict_entries {
        name_iid: 3
        string_value_iid: 3
      }
      dict_entries {
        name_iid: 15
        string_value_iid: 8
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
      dict_entries {
        name_iid: 16
        string_value_iid: 8
      }
    }
    type: TYPE_SLICE_END
    track_uuid: 3
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 7
    name: "Build"
    parent_uuid: 1
  }
}
packet {
  timestamp: 6
  trusted_packet_sequence_id: 1
  track_event {
    category_iids: 2
    debug_annotations {
      name_iid: 2
      dict_entries {
        name_iid: 3
        string_value_iid: 12
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
    }
    type: TYPE_SLICE_BEGIN
    name_iid: 7
    track_uuid: 7
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 8
    name: "Build"
    parent_uuid: 1
  }
}
packet {
  timestamp: 6
  trusted_packet_sequence_id: 1
  track_event {
    category_iids: 2
    debug_annotations {
      name_iid: 2
      dict_entries {
        name_iid: 3
        string_value_iid: 13
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
    }
    type: TYPE_SLICE_BEGIN
    name_iid: 8
    track_uuid: 8
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 9
    name: "Build"
    parent_uuid: 7
  }
}
packet {
  timestamp: 7
  trusted_packet_sequence_id: 1
  track_event {
    category_iids: 3
    debug_annotations {
      name_iid: 5
      dict_entries {
        name_iid: 6
        string_value_iid: 14
      }
      dict_entries {
        name_iid: 7
        string_value_iid: 5
      }
      dict_entries {
        name_iid: 8
        string_value_iid: 12
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
      dict_entries {
        name_iid: 9
        dict_entries {
          name_iid: 10
          string_value_iid: 6
        }
        dict_entries {
          name_iid: 11
          string_value_iid: 15
        }
      }
      dict_entries {
        name_iid: 12
        string_value_iid: 8
      }
    }
    type: TYPE_SLICE_BEGIN
    name_iid: 9
    track_uuid: 9
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  timestamp: 8
  trusted_packet_sequence_id: 1
  track_event {
    debug_annotations {
      name_iid: 13
      dict_entries {
        name_iid: 6
        string_value_iid: 14
      }
    }
    type: TYPE_SLICE_END
    track_uuid: 9
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  timestamp: 9
  trusted_packet_sequence_id: 1
  track_event {
    debug_annotations {
      name_iid: 14
      dict_entries {
        name_iid: 3
        string_value_iid: 12
      }
      dict_entries {
        name_iid: 15
        string_value_iid: 8
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
      dict_entries {
        name_iid: 16
        string_value_iid: 8
      }
    }
    type: TYPE_SLICE_END
    track_uuid: 7
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  timestamp: 10
  trusted_packet_sequence_id: 1
  track_event {
    debug_annotations {
      name_iid: 14
      dict_entries {
        name_iid: 3
        string_value_iid: 13
      }
      dict_entries {
        name_iid: 15
        string_value_iid: 8
      }
      dict_entries {
        name_iid: 4
        string_value_iid: 2
      }
      dict_entries {
        name_iid: 16
        string_value_iid: 8
      }
    }
    type: TYPE_SLICE_END
    track_uuid: 8
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
packet {
  timestamp: 10
  trusted_packet_sequence_id: 1
  track_event {
    debug_annotations {
      name_iid: 17
      dict_entries {
        name_iid: 15
        string_value_iid: 8
      }
      dict_entries {
        name_iid: 16
        string_value_iid: 8
      }
    }
    type: TYPE_SLICE_END
    track_uuid: 1
  }
  sequence_flags: 2
  timestamp_clock_id: 64
}
```


In `canary`, it looks wrong (to me)
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/3d4247c3-e992-4682-a21b-58dafca66f29">
The `script application for mylife-3` is a child of `Project evaluation for :proj-3` so I expected it to be displayed above the `Project evaluation for :proj-4`


But in `autopush`, it seems also wrong (to me)
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/097a56f3-105e-4e8c-9fd9-f268908da4f6">
- my tracks are not all on the same `Build` one, but that may actually be a good way to deal with the nesting (I'm talking about the inner 'Build' track for project evaluations
- but then why aren't the 'script application' tracks nested even more inside the project evaluation ones ?

**Comment by LalitMaganti** [comment] 2024-09-26 16:11
I think things here as working as intended: it will require some changes in how you are emitting the data to take advantage of the new features. So in response to your points:
1) There is no ordering guarantees between how slices are merged on tracks with the same name and the same parent. This guarantee has never existed and continues to not exist.
2) The new thing which *does* happen is that, if you specify different parent tracks, we now respect that and show it properly nested: basically we take the tree of tracks and display them correctly as a tree.
3) Now instead of *all tracks with the same name* being merged together regardless of parent_uuid, we now respect parent_uuid but *still* if multiple tracks have the same parent_uuid and same name, they will be merged with no guarantees on the ordering of slices.

Does that make sense?

**Comment by facewindu** [comment] 2024-09-27 13:44
> I think things here as working as intended: it will require some changes in how you are emitting the data to take advantage of the new features. So in response to your points:
> 
> 1. There is no ordering guarantees between how slices are merged on tracks with the same name and the same parent. This guarantee has never existed and continues to not exist.
> 2. The new thing which _does_ happen is that, if you specify different parent tracks, we now respect that and show it properly nested: basically we take the tree of tracks and display them correctly as a tree.
> 3. Now instead of _all tracks with the same name_ being merged together regardless of parent_uuid, we now respect parent_uuid but _still_ if multiple tracks have the same parent_uuid and same name, they will be merged with no guarantees on the ordering of slices.
> 
> Does that make sense?

Yes it does make sense.
I spent some time playing around with very simple slices and moving them around, changing the parent-child relationshipt, changing the track names.
I think I get it now :)
