### ISSUE TITLE
set timestamp format only affects timestamp and not duration formatting

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#622] opened 2023-11-05 23:17 UTC
I need both 'raw' to apply to the timestamp and duration.  I'm using Perfetto to display memory blocks that are not time-based.   And I really don't need 3 chunks of formatted values for each timestamp.  I just want the values even when I do use Perfetto for timings.

**Comment by LalitMaganti** [comment] 2023-11-05 23:59
Please see https://perfetto.dev/docs/faq#why-does-perfetto-not-support-lt-some-obscure-json-format-feature-gt- for our stance on supporting the Chrome JSON format.

Also keep in mind the JSON format was designed for Chrome: anyone other usecase was never officially supported, it just happened to work.

**Comment by LalitMaganti** [comment] 2023-11-06 00:00
Patches for supporting this are welcome but it's not something we'd get to ourselves.

**Comment by alecazam** [comment] 2023-11-06 00:24
Perfetto really needs to define a json format of it's own if this is unsupported.  Solely relying on protobuf use is limiting.

Also the "raw" timestamp when displayed raw isn't what's set from the json  It's converting the value to ns.  These are meant to be byte values. 

131072000 <- the value should be 131072.  It's adding 3 0's at the end.

**Comment by alecazam** [comment] 2023-11-06 00:26
This is not specifc to do with the unsupported Catapult json format, and is about not being able to control the formatting of duration in the app.   It's unclear why this command overrides the timestamp and not the duration.

**Comment by LalitMaganti** [comment] 2023-11-06 01:47
> Perfetto really needs to define a json format of it's own if this is unsupported. Solely relying on protobuf use is limiting.

We don't really have any intention of doing this in the short or medium term.

> Also the "raw" timestamp when displayed raw isn't what's set from the json It's converting the value to ns. These are meant to be byte values.

This matches the expected behaviour of Chrome traces as everything in the Perfetto world is always based on nanoseconds. As mentioned in the FAQ, if this doesn't happen to work for other usecases of chrome://tracing, then again patches welcome but not something we will get to ourselves.

**Comment by alecazam** [comment] 2023-11-06 17:10
This ia problem in general, not just with Catapult import.  I want to see the timestamp duration unformatted.  One of your devs stated that there should be more flexibility on this, but I haven't seen this change in 3 years.  

I need to see my duration as a single value (for timing and for memory tracking).  If it has to have 3 000 on the end, that is fine, but at least the Desired case below is way easier to parse that the formatted version that Perfetto currently displays.  This should also be show in a hover tip.

Displayed:1m 4s 8ms
Desired:    64008 s/mb/etc

**Comment by LalitMaganti** [comment] 2023-11-06 17:22
> This ia problem in general, not just with Catapult import. I want to see the timestamp duration unformatted. One of your devs stated that there should be more flexibility on this, but I haven't seen this change in 3 years.

We did have support for this at some point via supporting displayTimeUnit (see https://github.com/google/perfetto/issues/141#issuecomment-855405916, https://github.com/google/perfetto/commit/ee80bcb2b0466ecbb3d61ed2e5e9831d987ba4fc)  but it caused too many problems so we got rid of it. I don't think we'll be brining it back given how many problems it cause

> I need to see my duration as a single value (for timing and for memory tracking). If it has to have 3 000 on the end, that is fine, but at least the Desired case below is way easier to parse that the formatted version that Perfetto currently displays. This should also be show in a hover tip.

The problem here is coming between a disconnect between how you are wanting to use Perfetto and what Perfetto is fundamentally. Perfetto is not a charting system which can chart arbitrary data. It's a timeline viewer used for visualizing traces generated using Perfetto tooling. This is also the same for Catapult as well.

If Perfetto *happens* to work for cases outside our strict aims, that's great we're very happy that it can be useful. However, we have no intention of supporting cases where implementing a feature would go against the design direction or the aims of the project. For example, here, it does not make any sense for us to support a feature where timestamp is not actually a timestamp but something totally different.

This also ties with our approach to JSON vs protobuf: again our goal is not to be a charting tool for everyone but a way to visualize Perfetto traces. Perfetto traces are protobuf based so if you want the full feature set of Perfetto, then you need to use protobuf. We *happen* to support a JSON format for Chrome legacy usecases but *purely* for those usecases. For any other non-Chrome uses of Catapult, we will not go out of our way to support them.

**Comment by LalitMaganti** [comment] 2023-11-06 17:57
> In both cases, I want to see the unformatted timing. Just the timing that we specify, or a less formatted version (as per above)

My point is this is **not** a formatting issue, it is a conceptual issue. We do not track the "original" timestamp in the trace. We lose that information literally as soon as we parse it because, for Chrome traces it is irrelevant (as we always multiply by 1000). So it's not as simple as "let's show the raw data because we have it right there". It's more "we'd need to plumb the raw data all the way through trace processor and the UI because we don't track that information at all".

If you want to show the raw numbers (albeit still multipled by 1000), you can press "Ctrl+Shift+P" and choose the "Set Timestamp fomat" option
![image](https://github.com/google/perfetto/assets/679100/7504003e-93fe-4201-b193-74e28a8b5352)
 and switch to "Raw". Your timestamps will then display like this:
![image](https://github.com/google/perfetto/assets/679100/5e115bce-88b7-40ee-ac41-4cbdade4a8b9)

>  And also see the name/duration in a hover tip for super small values that are unreadable without having to change zoom.

Sure this is a separate problem entirely and one I agree we should solve.

**Comment by alecazam** [comment] 2023-11-06 18:12
Here's an example from our timings, not a memory trace.  We record all timings in ms, so showing them in seconds isn't ideal.

![image](https://github.com/google/perfetto/assets/3750359/967495c1-4862-4439-ab71-69c70943b3de)

**Comment by LalitMaganti** [comment] 2023-11-06 18:15
@stevegolton is there something better we can do here?

**Comment by stevegolton** [comment] 2023-11-08 10:53
HI @alecazam, IIUC you have two requests of the UI (let me know if I've missed anything).
1. Print durations in raw format.
2. Render a tooltip over the top of slice tracks showing the name and duration of the hovered slice.

1 is trivial to implement, but duration formatting is a controversial topic. It might be difficult to apply a single duration format to all parts of the UI. Let us discuss internally how this is going to work.

2 is an entirely reasonable request, but is a larger chunk of work. We are currently doing some work on tracks to reduce the total number of different track implementations, at which point it should be a lot easier to introduce features like this to all tracks in one go. Thus I'll be a while before we get around to this, but we are always happy to accept patches.

**Comment by alecazam** [comment] 2023-11-08 15:17
1. Print the duration in the same format that the graph and timestamp are printed in.   So honor set timestamp format.   
2. correct

**Comment by stevegolton** [comment] 2023-11-11 09:12
I've added a patch to address the duration issue, you can see the results [here](https://storage.googleapis.com/perfetto-ci-artifacts/20231109152753--cls-2818586-8--ui-clang-x86_64-release/ui/index.html). This might not be it's final form, though early feedback is welcome.

I also added the ability to change the time format from a dropdown menu on the timestamp/duration itself.

**Comment by alecazam** [comment] 2023-11-13 17:35
That duration formatting looks great, and consistent.  I can now read our time and memory profiles much easier.   One recommendation would be to have a "milliseconds" setting, since for games, out timings are all in milliseconds.  When you have 360Hz displays, seconds really is too big of a unit, and milliseconds is even getting to be too large (only 3ms per frame).  But I can get by and will often use seconds too.

**Comment by stevegolton** [comment] 2023-11-14 20:30
Great! Just waiting to get some feedback on it before landing.

I'll probably tackle the milliseconds in another CL.

**Comment by stevegolton** [comment] 2023-11-15 11:03
Just landed, should be available on the autopush channel soon.

**Closed** 2023-11-15 20:41 UTC
