### ISSUE TITLE
always in reading thread list stat

### ISSUE THREAD

**Issue by CTW8** [google/perfetto#830] opened 2024-06-21 07:59 UTC
After importing the trace file, it remains in the 'reading thread list' state. Many traces obtained from phones are like this. However, if converted to the old UI, they can be displayed.

**Comment by LalitMaganti** [comment] 2024-06-21 08:10
This is likely the same issue as discussed later on in https://github.com/google/perfetto/issues/818. It was resolved in autopush version of the UI but the fix has not been cherry-picked to stable.

Given that bug is open, I'm going to mark this as a duplicate of that and cherry-pick the fixes.

**Closed by LalitMaganti** 2024-06-21 08:10 UTC
