### ISSUE TITLE
[SDK] NewTrace Setup using a file descriptor on Windows produces corrupted trace files

### ISSUE THREAD

**Issue by zminjie** [google/perfetto#654] opened 2023-11-30 07:31 UTC
Hello,
I've been using Perfetto C++ Tracing SDK to trace events in my real-time C++ application. I followed the example code in the documentation to configure Perfetto with only InProcessBackend to record events from my application.

The tracing works perfectly when running on Linux but does not produce a readable file with the same code on Windows. The issue appears to be that when a NewTrace is created using a file descriptor on Windows, it'll produce a file that cannot be read by the Trace Processor or by the webapp on ui.perfetto.dev.

If a file descriptor is not used on Windows when creating the NewTrace, and the trace data is read at the end and output through an ofstream, then the resulting file is readable.

Initially, I thought that maybe the file descriptor API "open" and "close" are the issue since they are deprecated on Windows. But even using the proper WinAPI calls to manage the file descriptor, the resulting file still contains data that is not readable by the webapp.

**Comment by ddiproietto** [comment] 2023-11-30 11:42
Well I can't tell for sure what's going on without being able to reproduce the problem myself, but I has a strong suspicion this is a duplicate of https://github.com/google/perfetto/issues/327: You should pass `O_BINARY` as a flag to `open()`.

If that's not the case, please reopen this and provide an example code that I can use to reproduce the problem.

Thanks!

**Closed by ddiproietto** 2023-11-30 11:42 UTC
