### ISSUE TITLE
Exception occurred when referencing the example "Tracing Processor (Python)"

### ISSUE THREAD

**Issue by harveyxie22** [google/perfetto#895] opened 2024-09-22 06:46 UTC
Hello,

I think this example provided by the [official documentation](https://perfetto.dev/docs/analysis/trace-processor-python) may be misleading. 

In the Query chapter, a simple example is mentioned:

```python
from perfetto.trace_processor import TraceProcessor
tp = TraceProcessor(trace='trace.perfetto-trace')

qr_it = tp.query('SELECT ts, dur, name FROM slice')
for row in qr_it:
  print(row.ts, row.dur, row.name)
```

I followed the above steps and ran it on a Windows computer, and found that this example threw an exception.

```
Traceback (most recent call last):
  File "D:\Projects\Python\perfettodemo\demo1.py", line 12, in <module>
    main()
  File "D:\Projects\Python\perfettodemo\demo1.py", line 5, in main
    tp = TraceProcessor(trace=r'trace_file.perfetto-trace')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Python\perfettodemo\.venv\Lib\site-packages\perfetto\trace_processor\api.py", line 118, in __init__
    self.http = self._create_tp_http(addr)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Python\perfettodemo\.venv\Lib\site-packages\perfetto\trace_processor\api.py", line 188, in _create_tp_http
    url, self.subprocess = load_shell(self.config.bin_path,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Python\perfettodemo\.venv\Lib\site-packages\perfetto\trace_processor\shell.py", line 73, in load_shell
    raise Exception(
Exception: Trace processor failed to start. Try rerunning with verbose=True in TraceProcessorConfig for more detailed information and file a bug at https://goto.google.com/perfetto-bug or https://github.com/google/perfetto/issues if necessary.
```

I analyzed the cause of the exception and then fixed the problem in the following way:

```python
def main():
    tp = TraceProcessor(trace=r'trace_file.perfetto-trace', config=TraceProcessorConfig(
        bin_path=r'trace_processor_shell.exe'
    ))
    qr_it = tp.query('SELECT ts, dur, name FROM slice')
    for row in qr_it:
        print(row.ts, row.dur, row.name)


if __name__ == '__main__':
    main()
```

The current documentation is very confusing. Why does the operation fail when following the steps in the official documentation? I think the Perfetto team should rewrite this section so that more readers will not make the same mistake as I did.

**Comment by LalitMaganti** [comment] 2024-09-22 10:11
Hi. This documentation works totally fine but there is something going wrong on your machine specifically. If this was a general problem, a lot more people would have reported this issue. 

Likely you are unable to download the binary from GCS because there is some block on accessing GCS on your network: I've seen this happen a few times but theres not much we can do it your access to our tools is blocked. 

Closing because as I say nothing wrong on the Perfetto side.

**Closed by LalitMaganti** 2024-09-22 10:11 UTC

**Comment by LalitMaganti** [comment] 2024-09-22 13:56
Just confirmed by running on a fresh Windows install with official Python that the documented instructions work perfectly, exactly as described. As indicated in my previous message, there is some problem with your network which is causing the trace processor binary which should be downloaded (only happens the first time you run the script) to not be done so correctly.
