### ISSUE TITLE
CPU frequency doesn't showing

### ISSUE THREAD

**Issue by basketgd** [google/perfetto#233] opened 2022-01-20 01:33 UTC
Hello again

I tried to open systrace file, TraceViewer doesn't showing CPU frequency.
I thought cpu_frequency information wasn't in file, but it was in file.

So I tested as below steps
1. recored perfetto-trace (cpu_frequency showing)
2. convert perfetto-trace file to systrace file
3. open systrace file on trace viewer (cpu_frequency not showing)

[traces.zip](https://github.com/google/perfetto/files/7901568/traces.zip)
Please check attached file

**Comment by primiano** [comment] 2022-01-20 10:24
The systrace text importer doesn't support all the features of the proto trace format.
This is a dupe of https://github.com/google/perfetto/issues/72

I explained there the work that needs to be done. Patches welcome.

**Closed by primiano** 2022-01-20 10:24 UTC
