### ISSUE TITLE
Question about render UI, like android systrace log. Thank You.

### ISSUE THREAD

**Issue by showtestlog** [google/perfetto#550] opened 2023-08-06 19:38 UTC
`
             app-1454    (1265) [001] .... 1831645.995836: tracing_mark_write: B|1265|generateTokenForPredictions
             app-1454    (1265) [001] .... 1831655.995847: tracing_mark_write: E|1265

`
<img width="1360" alt="image" src="https://github.com/google/perfetto/assets/12830799/3c758a39-301a-43eb-ac6b-85e9cde86db5">

<img width="305" alt="image" src="https://github.com/google/perfetto/assets/12830799/3ea66aa6-6db4-4cf8-9818-cb7c422e86d4">

why can't be shown correctly?

**Comment by showtestlog** [comment] 2023-08-06 19:40
B and E are corresponding.

**Comment by chromy** [comment] 2023-08-07 09:39
Hey! :)

Please provide a minimised trace file for reproduction.

Thanks,
Hector

**Comment by LalitMaganti** [comment] 2023-08-08 10:54
On autopush I cannot reproduce this issue with the repro provided:
![image](https://github.com/google/perfetto/assets/679100/caf012da-5e0c-4b73-9eab-c5d26905cee9)

This issue should resolve itself once autopush UI reaches stable: feel free to switch to autopush in the "Flags" tab if you would like a fix for this issue before then.

**Closed by LalitMaganti** 2023-08-08 10:54 UTC
