### ISSUE TITLE
Perfetto UI does not display average time like it used to (and DOCS are lacking)

### ISSUE THREAD

**Issue by eladm-ultrawis** [google/perfetto#871] opened 2024-08-29 20:29 UTC
I am working with perfetto for years now using the C++ API. It is a great tracing API.

However, using the perfetto UI on my browser is a frustrating experience. 

I used to be able to 'area select' a bunch of traces and some nice metrics displayed like 'average wall time' and maybe even max time and min time which were quite useful.

Now, when area selecting my traces, I get weird metrics in are not useful - no average, no min, no max, only total duration.

![image](https://github.com/user-attachments/assets/db666e06-0ec4-414b-84c6-15399201913c)

1. Is this a bug?
2. can this be related to the tracing API version I use?
3. How can I show 'average time', 'max time', 'min time'? or maybe simply restore old behavior?

On a sidenote, the documentation of the UI part is very lacking. there is no step by step tutorials / videos anywhere online. and the official docs seems outdated. It is so frustrating because perfetto is such a great tool. It would be nice to know how to use the UI to do some BASIC things (hopefully without SQL / complex stuff)

Thanks for helping!

**Comment by LalitMaganti** [comment] 2024-08-29 20:47
> Is this a bug?

This is not a bug, the pivot table is mean to be a more configurable version of the previous tab: by clicking on the columns, you can customize them to show min/max/avg as you want. However, I agree that the pivot table UI is not as intuitive as the old slice aggregation view.

To that end, I've sent https://r.android.com/3249852 to also show the previous view.

> can this be related to the tracing API version I use?

No, the API version on device has no impact, this is purely UI side change

> How can I show 'average time', 'max time', 'min time'? or maybe simply restore old behavior?

By clicking on the three dots (see screenshot below), you can customize the table to add new columns and/or modify existing columns. By doing this, you can recover essentially the same view as you had before (plus with more customizability)

> On a sidenote, the documentation of the UI part is very lacking. there is no step by step tutorials / videos anywhere online. and the official docs seems outdated. It is so frustrating because perfetto is such a great tool. It would be nice to know how to use the UI to do some BASIC things (hopefully without SQL / complex stuff)

In general, we're aware of this issue. We're always caught between trying to make the UI more powerful to our existing userbase (who are quite power users and want flexibility, power and customization) and new users or users who just want to use the UI in a very simple way.

One of my aims for the next quarter or so is to provide more "guided" documenation to make it easier to on-board onto using Perfetto. I'll take onboard the feedback to also make using UI onboarding also easier: we've found internally at least that videos are by far the best way to use the UI so I'll look into making some tutorials on this.

Screenshot:
![image](https://github.com/user-attachments/assets/042e65f9-7520-4c05-9222-a4045957a21a)

**Comment by LalitMaganti** [comment] 2024-08-29 20:56
As a contrast see https://github.com/google/perfetto/issues/696: where someone was requesting adding exactly the featureset we added with pivot tables :)

**Comment by eladm-ultrawis** [comment] 2024-08-30 07:22
@LalitMaganti thank you for the quick response! I am looking forward to these tutorials.

I followed what you suggested and now the only thing that bothers me is the units: max / min are displayed in microseconds / milliseconds **(great!)** but average time which is the most important is displayed in an unclear format (nanoseconds?) 

Is there a way to have it the same format like min / max?

![image](https://github.com/user-attachments/assets/b1327b35-d3fe-487f-9d30-9a060868734c)

**Comment by LalitMaganti** [comment] 2024-08-30 13:54
> I followed what you suggested and now the only thing that bothers me is the units: max / min are displayed in microseconds / milliseconds (great!) but average time which is the most important is displayed in an unclear format (nanoseconds?)

https://r.android.com/3250814 fixes this. Yes the value are in nanoseconds.

> Also, I would add that: the changes are not persistent. I have to reconfigure every trace I am opening.

Ack yes. Agree this is annoying. We should figure out some UX to persist this.

**Comment by LalitMaganti** [comment] 2024-09-02 15:42
https://r.android.com/3249852  has landed so I'll be closing this issue since we've fixed the direct cause of this.

The docs work is something more long term and we've got that being tracked internally but it's definitely something we still want to do.

Thanks for filing, really appreciate the honest feedback!

**Closed by LalitMaganti** 2024-09-02 15:42 UTC

**Comment by LalitMaganti** [comment] 2024-11-25 11:22
We now show the slice aggregation tab by default and we show it first. The pivot table should only be shown as a backup.

**Comment by eladm-ultrawis** [comment] 2024-11-25 11:34
@LalitMaganti Forgive me, but what is the slice aggregation tab and how do I get there?

**Comment by LalitMaganti** [comment] 2024-11-25 11:44
Ahhhh seems like the fix is not yet on the stable UI yet. Please try switching to the canary UI, either by going to ui.perfetto.dev and then clicking on the "Canary" button or clicking on "Flags" on the sidebar then "Release Channel" and switching that to canary.

Then when you do a selection, you should get the slice aggregation tab:
![Image](https://github.com/user-attachments/assets/024073f7-058e-4cbf-80e9-9e2614e94546)

**Comment by eladm-ultrawis** [comment] 2024-11-25 19:00
Thanks!
