### ISSUE TITLE
Perefetto gets stuck at "PixelMemory#ShowTotalMemory already exists" and never recovers

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#923] opened 2024-11-04 05:42 UTC
My kram-profile app is hitting this error from Perfetto.  Once it occurs, I can't get another file to load.  This is Perfetto running in a Swift-wrapped WKWebView.  Seems to happen if I try to quickly go through the list of files.  This is reusing the same webview to load various clang -ftime-trace files. 

UI: https://ui.perfetto.dev/v47.0-1b4776303

RegistryError: Registrant dev.perfetto.PixelMemory#ShowTotalMemory already exists in the registry
 - RegistryError (frontend_bundle.js:3416:15)
 - register (frontend_bundle.js:3434:37)
 - registerCommand (frontend_bundle.js:84168:75)
 -  (frontend_bundle.js:84667:29)
 - onTraceLoad (frontend_bundle.js:84666:29)
 -  (frontend_bundle.js:84465:49)
 - doPluginTraceLoad (frontend_bundle.js:84460:38)
 -  (frontend_bundle.js:84425:38)

Trace: not available (ARRAY_BUFFER). Provide repro steps.
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)
Referrer:

**Comment by LalitMaganti** [comment] 2024-11-05 03:09
So this is clearly a race condition because it's a double registration error. The problem is that we have no other reports of this issue.

If there's a way to repro this in a bare browser I can take a look but otherwise if this is some race condition which specific to your app/your usage of WKWebView/a bug in WKWebView, we would not have the bandwidth to look into this.

**Comment by LalitMaganti** [comment] 2024-11-05 03:17
Also all of this code has been under *heavy* rework recently (for example, on HEAD `doPluginTraceLoad` function no longer even exists) so it's very possible that there was a bug which has been fixed.

**Comment by alecazam** [comment] 2024-11-05 16:59
Thanks, I'll keep checking if this goes away.  The inability to reuse the Perfetto web view to load different data is a problem.   It's already 600KB with nothing loaded.  But this new issue causes the app to never recover, and post the same error when I try to load a different trace file.   Something that broke in the last 2-3 months.

**Comment by LalitMaganti** [comment] 2024-12-22 00:56
We've hit this issue with manual loads as well and we think https://r.android.com/3428304 should resolve this issue.

**Comment by LalitMaganti** [comment] 2024-12-22 01:18
https://r.android.com/3428304 has landed, we believe this issue should be fixed. Thanks for reporting!

**Closed by LalitMaganti** 2024-12-22 01:18 UTC
Labels: bug
