### ISSUE TITLE
Include and compile error

### ISSUE THREAD

**Issue by LucasPa** [google/perfetto#146] opened 2021-06-23 08:42 UTC
Hi,

When compiling perfetto on my system, the following error was raised:

```
../thirdparty/perfetto-v16.1/perfetto.cc: Dans la fonction « std::string 
perfetto::base::Uint64ToHexStringNoPrefix(uint64_t) »:
../thirdparty/perfetto-v16.1/perfetto.cc:4754:52: erreur: expected « ) » before « PRIx64 »
4754 |   auto final_size = snprintf(&buf[0], max_size, "%" PRIx64 "", number);
     |                             ~                      ^~~~~~~
     |                                                    )

Dans le fichier inclus depuis ../thirdparty/perfetto-v16.1/perfetto.cc:27:
../thirdparty/perfetto-v16.1/perfetto.cc: Dans la fonction « protozero::{anonyme}::ParseFieldResult protozero:: 
 {anonyme}::ParseOneField(const uint8_t*, const uint8_t*) »:
../thirdparty/perfetto-v16.1/perfetto.cc:8653:38: erreur: expected « ) » before « PRIu32 »
8653 |     PERFETTO_DLOG("Skipping field %" PRIu32 " because its id > 0xFFFF",
```
A workaround I found is to add "#include \<cinttypes\>" in perfetto.h. But I guess a nicer correction could be made.

Best,

Lucas

**Comment by primiano** [comment] 2021-06-23 09:22
HI thanks for the report.
Sounds like a missing `inttypes.h` include indeed.
The missing include is probably in `string_utils.cc`, perfetto.cc is just the amalgamation of all sources.

Can I ask which compiler this came from? We cover our code with clang and gcc and none of them warned.
So beyond fixing this specific issue I am wondering: how did you spot this?

**Comment by LucasPa** [comment] 2021-06-23 13:16
Hi,

I use gcc 8.3. I did not anything special to spot this problem. The code I am working uses now perfetto, and I just bumped into this when compiling this code.

**Comment by primiano** [comment] 2021-06-23 13:21
This is probably because gcc8 has some slighly different headers that leak less includes, and this IWYU (include what you use) issue went unnoticed in other compilers. It didn't show up in ci.perfetto.dev which uses gcc-7.
Unfortunately we can't cover all possible toolchains, so every now and then this will happen.

Will send a patch soon for this, but will have no way to try and check if there are other issues. For the amalgamated sdk (perfetto.h/cc) The patch will likely have effect on the next release, v17, scheduled for early July (we do monthly releases).

Alternatively you could send a patch if you can verify the issue, that would be great.
See https://perfetto.dev/docs/contributing/getting-started for that.

**Comment by LucasPa** [comment] 2021-06-23 14:24
Thanks for this patch. I will wait for the v17 and I will keep you inform if the problem is then solved or not.

**Comment by LucasPa** [comment] 2021-06-24 08:23
Just an additional comment: 

> Sounds like a missing `inttypes.h` include indeed.

please note that I added the include cinttypes and not inttypes.h.

**Comment by primiano** [comment] 2021-06-24 09:16
I had a look at this and I am extremely confused, looks like that perfetto.cc has the right inttypes.h include before that point.
The first line you pasted comes from [`string_utils.cc`](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/base/string_utils.cc;l=198?q=%22auto%20final_size%20%3D%20snprintf(%26%22) which definitely has that include.

> please note that I added the include cinttypes and not inttypes.h.

I don't think it makes any difference for PRIx64 and the like, those are really #define(s) to string literals. There is no std:: namespace anyways.

Can I also ask you how to reproduce this? can you give me the full compiler cmdline?
I just tried with g++-10 @ v16.1 and seems to work:

```
g++-10 -Weverything -std=c++11 -c -o /tmp/xxx sdk/perfetto.cc -lpthread
(success, no warnings)
```

**Comment by LucasPa** [comment] 2021-06-24 12:24
The command-line run is:

`g++ -std=c++17 -Ofast -DNDEBUG -march=native --param inline-unit-growth=200 --param inline-min-speedup=1 -fopenmp -Wno-int-in-bool-context -Wno-misleading-indentation -Wno-deprecated-declarations -fPIC -I../thirdparty/perfetto-v16.1 ../thirdparty/perfetto-v16.1/perfetto.cc -c -o/stck/fpascal/RHEA/negev/build/thirdparty/perfetto-v16.1/perfetto.cc.1.o`

Please note that the same error is raised if I simplify it and use c++11 to like like your command (-Weverything is not known by my g++)
`g++ -std=c++11 ../thirdparty/perfetto-v16.1/perfetto.cc -c -o/stck/fpascal/RHEA/negev/build/thirdparty/perfetto-v16.1/perfetto.cc.1.o`

**Comment by primiano** [comment] 2021-06-24 12:45
Hmm weird, I just installed g++-8 and still cant' repro:
```$ g++-8 -std=c++11 perfetto.cc -c -o/tmp/perfetto.cc.1.o # works```

I start suspecting this is more related with your sysroot (the includes) than the compiler.

Out of curiosity can I ask you if you can try just this:

test.cc:
```
#include <inttypes.h>
#include <stdio.h>
int main(int argc, char**) { printf("%" PRIu32 "\n", argc); }
```

Then
` g++-8 -std=c++17 test.cc`

and if this fails (hopefully it should) then append `-E` to the invocation and copy the result somewhere. The output should show the preprocessor output.
Also, out of curiosity, if you open your /usr/include/inttypes.h, does it contain this?
```
/* Unsigned integers.  */
# define PRIu8    "u"
# define PRIu16   "u"
# define PRIu32   "u"
```

**Comment by LucasPa** [comment] 2021-06-24 13:16
Indeed compiling `test.cc` failed. Using `-E` gives the output written in the enclosed file `log.txt`. 

[log.txt](https://github.com/google/perfetto/files/6709450/log.txt)

My `/usr/include/inttypes.h` contains these three lines (which was expected now since adding `#include <cinttypes>` helped, isn't it?)

**Comment by primiano** [comment] 2021-06-24 13:24
Hmm that's really not expected and seems like a toolchain bug.

> My /usr/include/inttypes.h contains these three lines

Which lines? Unfortunately I cannot tell because -E only show the preprocessor "output" so doesn't show any define.
Out of curiosity, if you build with gcc instead (rather than g++) does it work?

inttypes.h is still expected to work in C++, AFAIK the difference beween inttypes.h and cinttypes should be just the std:: namespacing for functions (but this is a #define)

**Comment by primiano** [comment] 2021-06-24 13:26
Ooooh this might be relted with __STDC_FORMAT_MACROS ? Out of curiosity if you add -D __STDC_FORMAT_MACROS does it magically work?
Probably cinttypes adds that define to work around the issue?

**Comment by q-p** [comment] 2021-06-24 13:35
That sounds like you may be on to something (from https://en.cppreference.com/w/cpp/types/integer )

> The C99 standard suggests that C++ implementations should not define the above limit, constant, or format macros unless the macros __STDC_LIMIT_MACROS, __STDC_CONSTANT_MACROS or __STDC_FORMAT_MACROS (respectively) are defined before including the relevant C header (stdint.h or inttypes.h). This recommendation was not adopted by any C++ standard and was removed in C11. **However, some implementations (such as glibc 2.17) try to apply this rule, and it may be necessary to define the __STDC macros; C++ compilers may try to work around this by automatically defining them in some circumstances.**

It seems like replacing all `#include <inttypes.h>` by `#include <cinttypes>` could be a plausible fix / work-around, though.

**Comment by primiano** [comment] 2021-06-24 15:08
https://r.android.com/1746593 should fix it

**Comment by LucasPa** [comment] 2021-06-25 06:22
You got it! Adding `-D __STDC_FORMAT_MACROS` fixes the problem. 
Thanks for the fix!

**Comment by primiano** [comment] 2021-06-25 14:41
We switched all inttypes.h to <cinttypes> with r.android.com/1746593

Closing this. thanks for the report.

**Closed by primiano** 2021-06-25 14:41 UTC
