### ISSUE TITLE
perfetto can not use trace_process_shell open large perfetto file

### ISSUE THREAD

**Issue by ZiqiangGe** [google/perfetto#661] opened 2023-12-05 02:45 UTC
Hi，I downloaded the latest trace_process_shell from https://github.com/google/perfetto/releases/tag/v39.0
And then I use trace_processor_shell to open my trace file  like "./trace_processor_shell --httpd  xxx.perfetto-trace"，Prompt success
![image](https://github.com/google/perfetto/assets/18515372/1fd8501b-97e1-4cff-9edf-47b21c52e91f)
When i reload https://ui.perfetto.dev   there something wrong
![image](https://github.com/google/perfetto/assets/18515372/46c5d484-be58-41f3-984e-7ecb828cb63f)

`To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

Error: TimeSpan start [113242490188349] cannot be greater than end [0]
Error: TimeSpan start [113242490188349] cannot be greater than end [0]
    at assertTrue (https://ui.perfetto.dev/v39.0-54f9b3fc4/frontend_bundle.js:4440:16)
    at new HighPrecisionTimeSpan (https://ui.perfetto.dev/v39.0-54f9b3fc4/frontend_bundle.js:314618:35)
    at HighPrecisionTimeSpan.fromTime (https://ui.perfetto.dev/v39.0-54f9b3fc4/frontend_bundle.js:314621:17)
    at computeVisibleTime (https://ui.perfetto.dev/v39.0-54f9b3fc4/frontend_bundle.js:433619:57)
    at async TraceController.loadTrace (https://ui.perfetto.dev/v39.0-54f9b3fc4/frontend_bundle.js:433039:34)

v39.0-54f9b3fc4 54f9b3fc4aad6667a9c24604c8abb531ba310eef
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`

**Comment by kailums** [comment] 2023-12-05 07:24
yes, me too.

Frankly, i don't like this tool always update, and makes older version unavailable.

**Comment by LiangliangSui** [comment] 2023-12-05 08:33
You can use [trace_processor](https://perfetto.dev/docs/quickstart/trace-analysis) instead of trace_processor_shell. Trace_processor will automatically download and build using the latest trace_processor_shell. There is no need to manually download the latest trace_processor_shell. @ZiqiangGe @kailums 

It works fine using trace_processor.

**Comment by kailums** [comment] 2023-12-05 08:59
> You can use [trace_processor](https://perfetto.dev/docs/quickstart/trace-analysis) instead of trace_processor_shell. Trace_processor will automatically download and build using the latest trace_processor_shell. There is no need to manually download the latest trace_processor_shell. @ZiqiangGe @kailums
> 
> It works fine using trace_processor.

Thanks @LiangliangSui . it works.

**Comment by ZiqiangGe** [comment] 2023-12-05 09:20
> You can use [trace_processor](https://perfetto.dev/docs/quickstart/trace-analysis) instead of trace_processor_shell. Trace_processor will automatically download and build using the latest trace_processor_shell. There is no need to manually download the latest trace_processor_shell. @ZiqiangGe @kailums
> 
> It works fine using trace_processor.

Unfortunately, we have no access  commondatastorage.googleapis.com
Is there any other way?

"./trace_processor --httpd xxx.perfetto-trace"
`Downloading https://commondatastorage.googleapis.com/perfetto-luci-artifacts/6ba75cc5d93c39d4f86e2777709a460b30ce06fc/linux-amd64/trace_processor_shell
-=O=-                                               #    #     #   #           
curl: (7) Failed to connect to commondatastorage.googleapis.com port 443: timeout
Traceback (most recent call last):
  File "./trace_processor", line 294, in <module>
    run_perfetto_prebuilt(TRACE_PROCESSOR_SHELL_MANIFEST)
  File "./trace_processor", line 286, in run_perfetto_prebuilt
    bin_path = get_perfetto_prebuilt(manifest)
  File "./trace_processor", line 282, in get_perfetto_prebuilt
    sha256=manifest_entry['sha256'])
  File "./trace_processor", line 243, in download_or_get_cached
    subprocess.check_call(['curl', '-f', '-L', '-#', '-o', tmp_path, url])
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['curl', '-f', '-L', '-#', '-o', '/home/mi/.local/share/perfetto/prebuilts/trace_processor_shell.tmp', 'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/6ba75cc5d93c39d4f86e2777709a460b30ce06fc/linux-amd64/trace_processor_shell']' returned non-zero exit status 7`

**Comment by LalitMaganti** [comment] 2023-12-05 12:49
I've released Perfetto v40 which has the new version of trace processor which can contains the fix for this issue (r.android.com/2834432). Binaries can be found in the GitHub release as usual.

**Closed by LalitMaganti** 2023-12-05 12:49 UTC

**Comment by ZiqiangGe** [comment] 2023-12-07 03:23
> I've released Perfetto v40 which has the new version of trace processor which can contains the fix for this issue (r.android.com/2834432). Binaries can be found in the GitHub release as usual.

@LalitMaganti Thanks for release v40 version!

when i use  [linux-amd64.zip](https://github.com/google/perfetto/releases/download/v40.0/linux-amd64.zip) to  open my trace, it prompt success. Then i reload https://ui.perfetto.dev/   ,error occurred again.
Is it because of my Chrome version?


`[455.422] processor_shell.cc:1627 Trace loaded: 1307.75 MB in 98.38s (13.3 MB/s)
Error stats for this trace:
                                    name                                      idx                                   source                                    value 
---------------------------------------- ---------------------------------------- ---------------------------------------- ---------------------------------------- 
systrace_parse_failure                   [NULL]                                   analysis                                                                       18 
sorter_push_event_out_of_order           [NULL]                                   trace                                                                           2 
[455.422]             httpd.cc:99 [HTTP] Starting RPC server on localhost:9001
[455.422]            httpd.cc:104 [HTTP] This server can be used by reloading https://ui.perfetto.dev and clicking on YES on the "Trace Processor native acceleration" dialog or through the Python API (see https://perfetto.dev/docs/analysis/trace-processor#python-api).
[645.028]       http_server.cc:83 [HTTP] New connection
[645.029]      http_server.cc:231 [HTTP] POST /status [body=0B, origin="https://ui.perfetto.dev"]
[648.768]      http_server.cc:231 [HTTP] POST /status [body=0B, origin="https://ui.perfetto.dev"]
[648.784]       http_server.cc:83 [HTTP] New connection
[648.785]      http_server.cc:231 [HTTP] GET /websocket [body=0B, origin="https://ui.perfetto.dev"]
**Segmentation fault (core dumped)**`

![image](https://github.com/google/perfetto/assets/18515372/d6eb3565-10f1-4c80-ab13-938accec19db)

`To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

Uncaught Websocket closed (1006: )
"Websocket closed (1006: )"

v39.0-fa6ee75b6 fa6ee75b6f4a9374ade506697c65a8a73edc54be
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`

**Comment by ZiqiangGe** [comment] 2023-12-08 12:00
@LalitMaganti  Hi，please help and look at this issue again,Thanks

**Comment by LalitMaganti** [comment] 2023-12-08 18:07
https://r.android.com/2865716 should fix the crash but there is a much bigger problem in your trace: something is emitting events which huge negative timestamps in your trace and this is very much undefined behaviour.

I unfortunately don't have the bandwidth to figure out why that's happening but I'd very much look into that as that will cause you other problems.

**Comment by ZiqiangGe** [comment] 2023-12-11 03:29
@LalitMaganti Thanks for bugfix! 

The trace I provided last time was captured from Xiaomi 6. Today I also grabbed a big trace using  Samsung Tab S8 , and the perfetto reported the same error. Are there also a lot of negative timestamps in samsung trace?  
Samsung Trace link: https://github.com/ZiqiangGe/SamSung_trace/releases/download/samsung_trace_v1.0/SamSung_traces.zip

PS:I have been using the trace_processor_shell method to open large trace files since November 2021,it was normal before

**Comment by LalitMaganti** [comment] 2023-12-11 15:07
> Are there also a lot of negative timestamps in samsung trace?

Sorry as I mentioned I don't have the bandwidth to debug issues in your traces. If there is a bug in trace processor/UI, I can take a look but you'd need to look into the root cause of the negative timestamps on your side.

**Comment by ZiqiangGe** [comment] 2023-12-12 08:31
> Sorry as I mentioned I don't have the bandwidth to debug issues in your traces. If there is a bug in trace processor/UI, I can take a look but you'd need to look into the root cause of the negative timestamps on your side.

@LalitMaganti Hi, https://android-review.googlesource.com/c/platform/external/perfetto/+/2865716  patch is merged. Please help update the tag of V40，I  will tryagain with the latest V40 version. Thanks

**Comment by LalitMaganti** [comment] 2023-12-12 13:37
This crash is obscure enough that it's not doing a full respin of all of Perfetto for this.

However, we do release prebuilts without a full release occasionally and these have been pushed in https://r.android.com/2870534. They will not appear on GitHub but appear on GCS/CIPD as usual.

**Comment by ZiqiangGe** [comment] 2023-12-13 05:57
@LalitMaganti Hi,  When I use the latest trace_process_shell from https://commondatastorage.googleapis.com/perfetto-luci-artifacts/3e53e144bee271ec558363df2e561a77d7e0b789/linux-amd64/trace_processor_shell , It works fine !

Thanks Again!
