### ISSUE TITLE
heapprofd should post all free records as part of processing a send from the client

### ISSUE THREAD

**Issue by sukidog** [google/perfetto#136] opened 2021-05-18 13:48 UTC
I understand the overall architecture and the need to deal with frees differently than allocations. All frees need to be conveyed whereas allocations are coalesced and attributed based on the sampling interval the user has configured. This requires mitigating the overhead associated with frees and that's done by dealing with them in batches instead of individually.

However, I think there's an implementation deficiency in heapprofd, particularly in its efforts to batch the posting of frees to the main thread. Understandably, the unwinding worker thread doesn't want to post every free record in a send event individually. It wants to post them in bulk and so it stores all frees involved in the send inside client_data->free_records and then posts them to the main thread as a collection. This logic is in UnwindingWorker::HandleBuffer(), in the handling of a RecordType::Free record. You can see that it posts the accumulated free records only when the collection has filled up. This is problematic for reasons I'll explain in a bit. I believe that the collection should be posted regardless of size **at the completion of the send processing**. I.e., I believe UnwindingWorker::ReadAndUnwindBatch() should, as a final operation, post all collected free records.

How is the existing behavior problematic? It leads to dumps being coalesced in the timeline in a way that is detached from the sampling interval. A simple example will clarify what I mean.

Consider an application that does nothing but allocate and free a block of 1500 bytes every second. And let's say I want to profile that application with a sampling interval of 1024, and I ask for continuous dumps every second. Finally, I profile for a total of ten seconds. I should end up with a timeline that shows a dump every second. Instead, I end up with a timeline that shows a dump at the beginning and one at the end of the ten seconds. That's what I would expect if I set the sampling interval to, say, 64K. But having set it below the size of each allocation the app requests, I expect a dump every time I've asked for one--one every second. But it won't happen because the frees aren't posted to the heapprofd main thread until the client has called free() 1024 (kRecordBatchSize) times.

**Comment by primiano** [comment] 2021-05-18 14:09
@fmayer would know more.

A bunch of things are changes about frees, I am mainly thinking about
https://android-review.googlesource.com/c/platform/external/perfetto/+/1353613/

@sukidog which version of Android were you using?

**Comment by sukidog** [comment] 2021-05-18 14:54
I'm on Android 10. Thanks. I took a look at the CR and it appears the problem would not be addressed by it. In particular, the check in the heapprofd unwind thread to defer posting the frees until a full 1024 records have been received appears to [still be in place](https://android-review.googlesource.com/c/platform/external/perfetto/+/1353613/10/src/profiling/memory/unwinding.cc#313)

Reproducing it is very easy--you just need to wire a simple native program that allocates and frees a block of 1,500 bytes every second. Set the profiling options as I described above. If the resulting timeline doesn't show a dump every second, then the problem persists.

**Comment by sukidog** [comment] 2021-05-18 14:55
lol...in fact, I realize now that it's that CR that introduced the logic I find problematic :-)

**Comment by LalitMaganti** [comment] 2023-03-06 18:56
Closing because I don't think we have any plans to change this behaviour.

**Comment by ddiproietto** [comment] 2023-04-19 14:14
Duplicate of #477

**Closed by ddiproietto** 2023-04-19 14:14 UTC

**Comment by ddiproietto** [comment] 2023-04-19 14:15
Sorry for the delay, I realize this was fixed with https://r.android.com/2535722
