### ISSUE TITLE
Incomplete results querying slice thread state breakdown

### ISSUE THREAD

**Issue by lsfzlj** [google/perfetto#930] opened 2024-11-12 02:55 UTC
I am experiencing unexpected behavior with two SQL queries in my project. I have two queries: one includes a WHERE clause, and the other does not. Then I filter results with `df[df['name'] == "logLayerStats"]`.
However, the query without the WHERE clause returns fewer results than the one with the WHERE clause. I am not sure why this is happening.
# Environment
python=3.12.4
perfetto=0.11.0
Perfetto Android Example Trace
# Steps to Reproduce
You can try this python script to reproduce
```python 
from perfetto.trace_processor import TraceProcessor
trace_path = "example_android_trace_15s"
trace_processor = TraceProcessor(trace_path)
SLICE_SQL0 = """
DROP VIEW IF EXISTS slice_with_utid;
CREATE VIEW slice_with_utid AS
SELECT
  ts,
  dur,
  slice.name as slice_name,
  slice.id as slice_id, utid,
  thread.name as thread_name
FROM slice
JOIN thread_track ON thread_track.id = slice.track_id
JOIN thread USING (utid);

DROP TABLE IF EXISTS slice_thread_state_breakdown;
CREATE VIRTUAL TABLE slice_thread_state_breakdown
USING SPAN_LEFT_JOIN(
  slice_with_utid PARTITIONED utid,
  thread_state PARTITIONED utid
);
"""
SLICE_SQL1 = """
SELECT slice_id as id, slice_name as name, dur
FROM slice_thread_state_breakdown 
WHERE slice_name LIKE 'logLayerStats%';
"""
SLICE_SQL2 = """
SELECT slice_id as id, slice_name as name, dur
FROM slice_thread_state_breakdown 
WHERE slice_name LIKE 'log%';
"""
SLICE_SQL3 = """
SELECT slice_id as id, slice_name as name, dur
FROM slice_thread_state_breakdown;
"""
trace_processor.query(SLICE_SQL0)
df = trace_processor.query(SLICE_SQL1).as_pandas_dataframe()
print(df.shape)
df_q = df[df['name'] == "logLayerStats"]
print(df_q.shape)
df2 = trace_processor.query(SLICE_SQL2).as_pandas_dataframe()
print(df2.shape)
df2_q = df2[df2['name'] == "logLayerStats"]
print(df2_q.shape)
df3 = trace_processor.query(SLICE_SQL3).as_pandas_dataframe()
print(df3.shape)
df3_q = df3[df3['name'] == "logLayerStats"]
print(df3_q.shape)
```
# Expected Result
df_q.shape / df2_q.shape / df3_q.shape should be the same.
# Actual Result
df2_q.shape is (802, 3) and df3_q.shape is (780, 3).
Also, in some trace files all three are different(not just "logLayerStats").

**Comment by LalitMaganti** [comment] 2024-11-12 03:18
So very unfortunately, this is sort of working as intended for span join. Specifically, there is a very important warning in the documentaiton:
![Image](https://github.com/user-attachments/assets/0b8023a0-6106-47d9-9ef3-b34e2d5e78ab)

In your query, this restriction is not adhered to: the slice table has overlapping spans even for a given utid since, for a single thread, there are slices are different depths.

I appreciate this query probably came from the page I wrote myself (https://perfetto.dev/docs/analysis/common-queries). Clearly I did not think about span join's restriction carefully enough when I wrote this. I should really removce this page, neither query here is actually the best practice for how to compute information today.

Specifically, for computing CPU time, the modern suggestion is to use the thread_slice_cpu_time table (https://perfetto.dev/docs/analysis/stdlib-docs#slices-cpu_time): this can be joined with the thread table to much more simply compute the CPU time for a slice.

In the medium-long term, we're aware of the large amount of sharp edges around span join and it is something we very much want to replace with something better. Unfortunately, the work on that replacement was paused due to some higher priority work but it's very much something we will get back to as soon as we can.

**Comment by lsfzlj** [comment] 2024-11-12 08:08
Thanks for your reply! I also use below SQL to do slices thread time count, I don't quite remember where it comes from but I guess it has the same problem. What's the substitution？
```
DROP VIEW IF EXISTS slice_with_utid;
CREATE VIEW slice_with_utid AS
SELECT
  ts,
  dur,
  slice.name as slice_name,
  slice.id as slice_id, utid,
  thread.name as thread_name
FROM slice
JOIN thread_track ON thread_track.id = slice.track_id
JOIN thread USING (utid)
WHERE slice_name LIKE 'TLiveTrace%';

DROP TABLE IF EXISTS slice_thread_state_breakdown;
CREATE VIRTUAL TABLE slice_thread_state_breakdown
USING SPAN_LEFT_JOIN(
  slice_with_utid PARTITIONED utid,
  thread_state PARTITIONED utid
);

WITH running_data AS (
    SELECT 
        slice_name,
        SUM(dur) AS dur
    FROM slice_thread_state_breakdown
    WHERE state = 'Running'
    GROUP BY slice_name
),
runnable_data AS (
    SELECT 
        slice_name,
        SUM(dur) AS dur
    FROM slice_thread_state_breakdown
    WHERE state = 'R' or state = 'R+'
    GROUP BY slice_name
),
sleeping_data AS (
    SELECT 
        slice_name,
        SUM(dur) AS dur
    FROM slice_thread_state_breakdown
    WHERE state = 'S' or state = 'D'
    GROUP BY slice_name
)

SELECT DISTINCT 
    r.slice_name AS name,
    COALESCE(runnable_data.dur, 0) AS runnable_dur,
    COALESCE(sleeping_data.dur, 0) AS sleeping_dur
FROM slice_thread_state_breakdown r
LEFT JOIN runnable_data ON r.slice_name = runnable_data.slice_name
LEFT JOIN sleeping_data ON r.slice_name = sleeping_data.slice_name
ORDER BY name;
```

**Comment by LalitMaganti** [comment] 2024-11-12 10:44
I think you can use the `sched_time_in_state_for_thread_in_interval` table (https://perfetto.dev/docs/analysis/stdlib-docs#sched-time_in_state) to do this (also I'm replacing your slice_with_utid table with thread_slice from the stdlib - https://perfetto.dev/docs/analysis/stdlib-docs#slices-with_context):
```
INCLUDE PERFETTO MODULE slices.with_context;
INCLUDE PERFETTO MODULE sched.time_in_state;

SELECT
  t.name,
  SUM(IIF(s.state = 'R' OR s.state = 'R+', s.dur, NULL)) AS runnable_dur,
  SUM(IIF(s.state = 'S' OR s.state = 'D', s.dur, NULL)) AS sleeping_dur
FROM thread_slice t
JOIN sched_time_in_state_for_thread_in_interval(t.ts, t.dur, t.utid) s
GROUP BY t.name
ORDER BY t.name;
```

This is not the most efficient query but is the simplest one by far: it may run very slow on larger traces. Really we should add something in the standard library similar: let me know if it's too slow and I can look into writing something up.

**Comment by LalitMaganti** [comment] 2024-11-12 10:55
Ignore my previous message: it was actually too slow even on the example trace while I was testing. Will look into coming up with something better.

**Comment by LalitMaganti** [comment] 2024-11-12 12:29
So I landed https://r.android.com/3345071 which from v49+ would allow you to write simply:

```
INCLUDE PERFETTO MODULE slices.time_in_state;

SELECT
  name,
  SUM(IIF(state = 'R' OR state = 'R+'), dur, NULL) AS runnable_dur,
  SUM(IIF(state = 'S' OR state = 'D'), dur, NULL) AS sleeping_dur
FROM thread_slice_time_in_state
GROUP BY name
```

If you need this immediately, as a temporary solution, you can copy the contents of [1] to create the `thread_slice_time_in_state` table. So instead of `INCLUDE PERFETTO MODULE slices.time_in_state;` above, you do:

```
INCLUDE PERFETTO MODULE intervals.intersect;

CREATE PERFETTO TABLE thread_slice_time_in_state AS
SELECT
  ii.id_0 AS id,
  ts.name,
  ts.utid,
  ts.thread_name,
  ts.upid,
  ts.process_name,
  tstate.state,
  tstate.io_wait,
  tstate.blocked_function,
  SUM(ii.dur) AS dur
FROM _interval_intersect!(
  (
    (SELECT * FROM thread_slice WHERE utid > 0 AND dur > 0),
    (SELECT * FROM thread_state WHERE dur > 0)
  ),
  (utid)
) ii
JOIN thread_slice ts ON ts.id = ii.id_0
JOIN thread_state tstate ON tstate.id = ii.id_1
GROUP BY ii.id_0, tstate.state, tstate.io_wait, tstate.blocked_function
ORDER BY ii.id_0;
```

Please do not rely on this in the long term though: `_interval_intersect` is an internal implementation detail of trace processor and it *will* change or be removed at some point.

Will close this out as I think we've now solved the questions posed by this bug. Thanks for filing!

**Closed by LalitMaganti** 2024-11-12 12:29 UTC
