### ISSUE TITLE
A timestamp display issue of perfetto

### ISSUE THREAD

**Issue by Oplus-Keven** [google/perfetto#735] opened 2024-03-08 08:01 UTC
We have a perfetto trace displayed on the perfetto ui and found that Absolute Time will not change. 
[perfetto_trace.zip](https://github.com/google/perfetto/files/14535351/perfetto_trace.zip)

**Comment by Oplus-Keven** [comment] 2024-03-12 03:13
Unit_multipiler.ns is the unit, representing 1000000 ns, and represents the unit as ms
Timestamp=1704285386714 ms=1704285396714 * 1000000 ns
If unit_multipiler_s is 1, then the timestamp should be multiplied by 1000000 to correct.
Is it because this unit_multipileryns does not support setting values other than 1?

**Comment by stevegolton** [comment] 2024-03-12 06:49
I'm away from my laptop this week so just replying on my phone so please bear with me.

The multiplier works as of the tip of main & the latest releases. I believe it used to be broken (i.e. you could set it's value to anything but the multiplier wasn't applied) but was fixed in a patch fairly recently ~ a few months ago, which might be causing some confusion.

Your first clock snapshot with clock id = 1 (realtime) looks fine. It's the second snapshot with clock id = 6 (boot time) which looks troublesome.

Clock snapshots pin down certain clocks with the one you're using to timestamp packets in a trace. In your trace you're using clock id 6 for timestamping packets, and your clock snapshot is providing a link between clocks 1 and 6.

The issue is that the first clock snapshot must be defined before the first packet, otherwise abs timestamps will be clamped like you're seeing. Because of the multiplier on this packet, its timestamp is far in the future compared to the timestamps of packets in your trace, so all abs times are clamped. Note: The multiplier does not apply to packet timestamps, only the clock value in the clock snapshot packet.

If you are generating traces synthetically, you have two options:
1. Remove the multiplier I outlined in red in my previous comment.
2. Multiply all timestamps in your packets by 1000000.

I can't be sure because I don't know the scale of your trace.

If you're recording traces using a recording tool, please let us know which one you are using because it might have a bug.

**Comment by Oplus-Keven** [comment] 2024-03-12 07:31
This trace was generated by ourselves, and we can guarantee that the first packet is a snapshot. 

Can you fix the issue of the ineffective setting of unit_multipiler.ns? Because according to the definition, this field can be set to different values.
Your suggestion involves a lot of modifications for us, and we only need to be precise to the point of ms.
@stevegolton

**Comment by stevegolton** [comment] 2024-03-12 18:10
Can you elaborate on what is ineffective about unit_multiplier_ns? It's working as intended as far as I can see.

**Comment by Oplus-Keven** [comment] 2024-03-13 07:38
As discussed earlier, we only need to be precise to ms, so the timestamps unit in each packet is ms. When I set unit_multipiler_ns to 1000000, the Absolute Time on the Perfetto UI interface cannot be updated properly.
@stevegolton

**Comment by stevegolton** [comment] 2024-03-13 09:31
You might have to use a custom clock for the multiplier to take effect across the trace packets. I don't think it applies to the built-in clocks.

https://perfetto.dev/docs/concepts/clock-sync

I think I've reached the limit of what I can do without a laptop. Perhaps @aMayzner or @ddiproietto could take over?

**Comment by LalitMaganti** [comment] 2024-03-14 15:30
Steve is absolutely correct: builtin clocks are not allowed to set multipliers or similar. If you need support for it, please use a custom sequence scoped clock.

**Closed by LalitMaganti** 2024-03-14 15:30 UTC
